// VALORES PRIMITIVOS - IMUTÁVEL

// STRING, NUMBER, BOOLEAN, UNDEFINED, NULL (BIGINT, SYMBOL)
//SEUS VALORES SÃO APENAS COPIADOS:

let a = 'Tiago';
let b = a;

console.log(a, b);

//MUDANDO O VALOR DE 'a' NÃO INTERFERE NO VALOR DE 'b', POIS ELE FOI COPIADO E ESTÁ SALVO DENTRO DA VARIÁVEL

a = 'Miguel';
console.log(a, b);
